<?xml version="1.0" encoding="UTF-8"?>
<!-- DTD 추가 -->
<!DOCTYPE memberList
[
<!ELEMENT memberList (memberInfo+)>
<!ELEMENT memberInfo (name, tel, email, curriculumn, hobby, zipCode)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT tel (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT curriculumn (sub+)>
<!ELEMENT sub (#PCDATA)>
<!ELEMENT zipCode (#PCDATA)>
<!ELEMENT hobby (#PCDATA)>
<!ATTLIST memberInfo mid CDATA #IMPLIED>

]>
<!-- #REQUIRED 속성은 반드시명시 -->
<!-- #IMPLIED 명시되기도, 아니기도하다-->
<!-- #FIXED 특정값 : 특정값으로 고정되어 사용 -->
<memberList>
	<memberInfo mid="1">
		<name>김상기</name>
		<tel><![CDATA[010-5693-4223]]></tel>
		<email><![CDATA[ckacl0233@naver.com]]></email>
		<curriculumn>
			<sub>JAVA SE</sub>
			<sub>ORACLE</sub>
			<sub><![CDATA[Servlet&JSP]]></sub>
		</curriculumn>
		<hobby>talking</hobby>
		<zipCode>01234</zipCode>
	</memberInfo>
	
	<memberInfo mid="2">
		<name>김민성</name>
		<tel><![CDATA[010-5693-4223]]></tel>
		<email><![CDATA[ckacl0233@naver.com]]></email>
		<curriculumn>
			<sub>JAVA SE</sub>
			<sub>ORACLE</sub>
			<sub><![CDATA[Servlet&JSP]]></sub>
		</curriculumn>
		<hobby>talking</hobby>
		<zipCode>01234</zipCode>
	</memberInfo>
</memberList>